/* Admin tour script */
(function($){

	$.main_AdminTour = function(){
			
	//hopscotch.endTour(true);

	   var lnTour	= {};
	   
	   if(cc.adminLang == "de"){
		   lnTour	= { nextBtn: "weiter",
						prevBtn: "zurück",
						doneBtn: "fertig",
						skipBtn: "überspringen",
						closeTooltip: "schließen",
						start: "Tour starten",
						taskBtn: "weitere Hilfe?",
						title1: "Willkommen im Adminbereich",
						title2: "Dashboard",
						title3: "Neue Seiten",
						title4: "Seiteninhalte",
						title5: "Seitenstruktur",
						title6: "Module",
						title7: "Medien",
						title8: "Gängige Aufgaben",
						title9: "Vorschaumenü",
						title10: "Tour Ende",
						text1: "Concise-WMS-Tour starten.",
						text2: "Hauptbereich: Übersichtsbereich mit Meldungen.",
						text3: "Neue Seiten für die Website anlegen.",
						text4: "Inhalte und Einstellungen für Seiten anlegen und bearbeiten.",
						text5: "Menüstruktur für die Website bearbeiten.",
						text6: "Inhalte verwalten, die über Module gesteuert werden, z.B. <b>Bildergalerien</b> oder <b>Nachrichten</b>.",
						text7: "Dateien und Medien hochladen und verwalten.",
						text8: "Aufgabenbereich mit Links zu gängigen Seiten im Adminbereich.",
						text9: "Menü mit der aktuellen Webseitenstruktur für den direkten Aufruf bestimmter Seiten.",
						text10: "Los geht's mit dem Bearbeiten der Seiteninhalte."
					  };
	   }else{
		   lnTour	= {	start: "Start tour",
						taskBtn: "need further help?",
						title1: "Welcome to admin backend",
						title2: "Dashboard",
						title3: "New pages",
						title4: "Page contents",
						title5: "Menu structure",
						title6: "Modules",
						title7: "Media",
						title8: "Common tasks",
						title9: "Preview menu",
						title10: "End of tour",
						text1: "Start Concise WMS tour.",
						text2: "Main area: overview and important notifications.",
						text3: "Add new pages to your website.",
						text4: "Add and edit contents of your web pages.",
						text5: "Edit website's menu structure.",
						text6: "Manage contents generated by modules, e.g. <b>image galleries</b> or <b>news</b>.",
						text7: "Updload and manage media files.",
						text8: "Task area with links to common admin task pages.",
						text9: "Menu representing current website structure enabling direct launch of certain pages.",
						text10: "Let's start with editing contents."
					  };
		   
	   }
		
		// Define the tour!
		var optsTour = {
		  id: "cwms-admin-tour",
		  i18n: lnTour,
		  showPrevButton: true,
		  steps: [
			{
			  title: lnTour.title1,
			  content: lnTour.text1,
			  target: "logoDiv",
			  placement: "bottom"
			},
			{
			  title: lnTour.title2,
			  content: lnTour.text2,
			  target: document.querySelector(".adminTask-main .cc-section-heading"),
			  placement: "bottom",
			  xOffset: "center",
			  arrowOffset : "center"
			},
			{
			  title: lnTour.title3,
			  content: lnTour.text3,
			  target: "mainMenuItem-new",
			  placement: "right"
			},
			{
			  title: lnTour.title4,
			  content: lnTour.text4,
			  target: "mainMenuItem-edit",
			  placement: "right"
			},
			{
			  title: lnTour.title5,
			  content: lnTour.text5,
			  target: "mainMenuItem-sort",
			  placement: "right"
			},
			{
			  title: lnTour.title6,
			  content: lnTour.text6,
			  target: "mainMenuItem-modules",
			  placement: "right"
			},
			{
			  title: lnTour.title7,
			  content: lnTour.text7,
			  target: "mainMenuItem-file",
			  placement: "right"
			},
			{
			  title: lnTour.title8,
			  content: lnTour.text8,
			  target: "adminMain",
			  placement: "top",
			  xOffset: "center",
			  arrowOffset : "center"
			},
			{
			  title: lnTour.title9,
			  content: lnTour.text9,
			  target: "mainMenu",
			  placement: "left"
			},
			{
			  title: lnTour.title10,
			  content: lnTour.text10,
			  target: ".headerBox",
			  placement: "bottom",
			  xOffset: "center",
			  arrowOffset : -9999,
			  showCTAButton: true,
			  ctaLabel: lnTour.taskBtn,
			  onCTA: function(){
				hopscotch.endTour(true);
				$.doAjaxAction("admin?task=help");
			 },
			}
		  ]
		};
		
		var startTourBtn	= $('<div id="adminTourNav" class="iconPanel-top"><button title="' + lnTour.start + '" class="cc-button button btn cc-button adminTourHint button-icon-only button-small"><span aria-hidden="true" class="cc-admin-icons cc-icons cc-icon-compass2">&nbsp;</span></button></div>');
		
		startTourBtn.css('transition','all 0.5s ease');
		
		startTourBtn.prependTo('#iconPanelTop');
		
		// Animate if first call
		if(!$.cookie('conciseLog')){
			startTourBtn.delay(1000).fadeTo(300, 0.25, function(){
				startTourBtn.children('button').showTitleTag();
				startTourBtn.css('transform','scale(1.25)');
			}).delay(100)
			.fadeTo(300, 0.75)
			.delay(100)
			.fadeTo(100, 0.25)
			.delay(100)
			.fadeTo(300, 0.75)
			.delay(100)
			.fadeTo(100, 0.25)
			.delay(100)
			.fadeTo(300, 1, function(){
				startTourBtn.css('transform','scale(1)');
				//startTourBtn.children('button').restoreTitleTag();
			});
		}
		
		startTourBtn.bind("click", function(){
		
			// Start the tour!
			hopscotch.startTour(optsTour);
		
		});
	};
})(jQuery);
